### ISSUE TITLE
THIS IS NOT A BUG

### ISSUE THREAD

**Issue by faanskit** [Fufs/pysolplanet#2]
Thanks for the amazing work. I've been exploring the endpoints/scrips you provided and want to learn how they were found.
In particular I would like to find endpoints/scripts for collecting historical data. 

The WiFi dongle should have at least the capability to store up to 3-days of data according to sales information. Therefore it would be interesting to know if you have additional endpoints/scripts that are yet to discover.

Also, I notice that port 1883 seems to be exposed. 1883 is normally for MQTT. 

1.)
Can you please share any documentation you have?

2.)
Can you please share any reverse engineering insights you may have?

3.)
Do you know if there is an endpoint/script for historical data?

4.)
Do you have any insights on this WiFi dongle and MQTT?

BR, /M

**Comment by Fufs** [comment]
Hi, 

This script is quite basic because I only had 2 weeks to play with this inverter and dongle. But to answer your questions:

1. All the documentation I have is in the wiki section. I'll try to add more to it next time I'll have access to it.

2. I started with a nmap port scan. I found 2 open ports, iirc, but 8484 was the one. It listens for http requests on that port. I then setup a proxy on my computer and connected my phone to it. Using Wireshark I sniffed http packets going between the dongle and my phone. That's how I was able to discover the endpoint scripts and necessary query strings. Rest is brute force - trying different values for the the query strings and seeing the response.

3. I haven't been able to find any of that in the app but maybe I haven't looked hard enough. Please give it a go, and tell me what you find.

4. To the best of my knowledge it doesn't have support MQTT, only REST API. I haven't seen any mention of MQTT while scrolling through the local mode of the app. I think the second port might be used for discovery in the app, but I don't quite remember what my finding where.

**Comment by faanskit** [comment]
**Thanks**,

If you give me access to the Wiki I can add some more information from my first analysis. I can help document what I've learned so far. I don't think the Wiki followed the fork. But, better I document in your Wiki.

I was not aware that the app communicated directly with the inverter, I just assumed it fetched data from the cloud. _Interresting_.
Next time I have access to the system I will have to run `mitmproxy` to see more what happens. Also I may be able to ask for additional permissions in the app for extra features. With some luck I may get installer privileges'.

The Solplanet app shows daily, monthly graphs of data. Hopefully it fetch it locally. Which app did you use? Solplanet?
Did your trace see how the app discovered the unit? mDNS or maybe got it from the Cloud?

My speculation on 1883 is that the inverter send data to the cloud using MQTT. Since this is same supplier as Zeversolar, it is likely so.

/M
ps. If you enable the discussion section in github we can move this thread there...

**Comment by Fufs** [comment]
I used the Aiswei app (before they switched to the Solplanet app around jan). To be able to communicate directly without the cloud, you need to go to the local mode (from the login screen). As for the fetching, I've only been able to retrieve current stats but you can easily log in a database or, the way I've done it, in home assistant.
